/* Generated By:JavaCC: Do not edit this line. CalendarParserConstants.java */
package edu.curtin.calendarparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalendarParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVENT_DECLARATION = 5;
  /** RegularExpression Id. */
  int PLUGIN_DECLARATION = 6;
  /** RegularExpression Id. */
  int SCRIPT_DECLARATION = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int TIME = 9;
  /** RegularExpression Id. */
  int DURATION = 10;
  /** RegularExpression Id. */
  int ALL_DAY = 11;
  /** RegularExpression Id. */
  int STRING_QUOTE = 12;
  /** RegularExpression Id. */
  int SCRIPT_CONTENT = 13;
  /** RegularExpression Id. */
  int STRING_NORMAL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"event\"",
    "\"plugin\"",
    "\"script\"",
    "<DATE>",
    "<TIME>",
    "<DURATION>",
    "\"all-day\"",
    "<STRING_QUOTE>",
    "<SCRIPT_CONTENT>",
    "<STRING_NORMAL>",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\":\"",
  };

}
